export enum FirstDayOnboardingFieldEnum {
  TOOLS = 'Tools',
  GITHUB_ACCOUNT = 'Github Account',
  EMAIL_TWO_FACTOR_AUTH_SCREENSHOT = 'Email Two Factor Auth Screenshot',
  GITHUB_TWO_FACTOR_AUTH_SCREENSHOT = 'Github Two Factor Auth Screenshot',
  E_SIGN = 'E-Signature',
  TWO_X_TWO_PICTURE = 'Picture',
  PROBATIONARY_CONTRACT = 'Probationary Contract',
  SSS_LOAN = 'SSS Loan',
  PAGIBIG_LOAN = 'PAGIBIG Loan',
  SSS_MONTHLY_AMORTIZATION = 'SSS Monthly Amortization',
  PAGIBIG_MONTHLY_AMORTIZATION = 'PAGIBIG Monthly Amortization',
}

export enum PersonalInformationFieldEnum {
  FIRST_NAME = 'First Name',
  MIDDLE_NAME = 'Middle Name',
  LAST_NAME = 'Last Name',
  POSITION = 'Position',
  SSS_NUMBER = 'SSS Number',
  TIN_NUMBER = 'TIN Number',
  PHILHEALTH_NUMBER = 'Philhealth Number',
  PAGIBIG_NUMBER = 'PAGIBIG Number',
  BIRTHDAY = 'Birthday',
  EDUCATIONAL_BACKGROUND = 'Educational Background',
  CONTACT_NUMBER = 'Contact Number',
  MOBILE_CARRIER = 'Mobile Carrier',
  ADDRESS = 'Address',
  EMAIL = 'Email',
  SLACK_ACCOUNT = 'Slack Account',
  EMERGENCY_NAME = 'Emergency - Name',
  EMERGENCY_RELATIONSHIPP = 'Emergency - Relationship',
  EMERGENCY_ADDRESS = 'Emergency - Address',
  EMERGENCY_CONTACT_NUMBER = 'Emergency - Contact Number',
}

export enum ATMApplicationsFieldEnum {
  FIRST_NAME = 'First Name',
  MIDDLE_NAME = 'Middle Name',
  LAST_NAME = 'Last Name',
  MOTHER_NAME = "Mother's Name",
  MARITAL_STATUS = 'Marital Status',
  GENDER = 'Gender',
  PERMANENT_ADDRESS = 'Permanent Address',
  CITY_MUNICIPALITY_PROVINCE = 'City/Municipality/Province',
  ZIP_CODE = 'Zip Code',
  CONTACT_NUMBER = 'Contact Number',
  BIRTH_PLACE = 'Birth Place',
  BIRTHDAY = 'Birthday',
  POSITION = 'Position',
  TIN_NUMBER = 'TIN Number',
  SSS_NUMBER = 'SSS Number',
}

export enum LaptopMonitoringFieldEnum {
  OWNER = 'Owner',
  BRAND = 'Brand',
  MODEL = 'Model',
  SERIAL_NUMBER = 'Serial Number',
  COMPANY_TAG = 'Company Tag',
  ISSUE_DATE = 'Issue Date',
  CONDITION = 'Condition',
  HAS_ISSUE_PROBLEM = 'Has Issue/Problem',
  ISSUE_PROBLEM = 'Issue/Problem',
  OS = 'OS',
  RAM = 'RAM',
  PROCESSOR = 'Processor',
  VIDEO_MEMORY = 'Video Memory',
  OTHER_NOTE = 'Other Note',
}
